apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment-add-task
spec:
  replicas: {{ .Values.addtask.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app-add-task
  template:
    metadata:
      name: demo-pod
      labels:
        app: {{ .Release.Name }}-app-add-task
    spec:
      containers:
      - name: {{ .Release.Name }}-container
        image: {{ .Values.common.ContainerRegistryUrl }}/{{ .Values.addtask.image.name }}:{{ .Values.addtask.image.tag }}
        ports:
        - containerPort: {{ .Values.addtask.targetPort }}
        env:
        - name: CONNECTION_STRING
          value: {{ .Values.common.ConnectionString }}
  strategy:
    type: RollingUpdate
