apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-add-task-svc
spec:
  selector:
    app: {{ .Release.Name }}-app-add-task
  ports:
  - port: {{ .Values.addtask.servicePort }}
    targetPort: {{ .Values.addtask.targetPort }}
