apiVersion: apps/v1
kind: Service
metadata:
  name: {{ .Release.Name }}-add-task-api
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
  - port: {{ .Values.addtask.servicePort }}
    targetPort: {{ .Values.addtask.Port }}
