apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment-todo-ui
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app-todo-ui
  template:
    metadata:
      name: demo-pod
      labels:
        app: {{ .Release.Name }}-app-todo-ui
    spec:
      containers:
      - name: {{ .Release.Name }}-container
        image: {{ .Values.common.ContainerRegistryUrl }}/{{ .Values.ui.image.name }}:{{ .Values.ui.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.ui.targetPort }}
  strategy:
    type: RollingUpdate