apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-ui-svc
spec:
  selector:
    app: {{ .Release.Name }}-app-todo-ui
  ports:
  - port: {{ .Values.ui.servicePort }}
    targetPort: {{ .Values.ui.targetPort }}
