apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-delete-task-ingress
spec:
  ingressClassName: {{ .Values.deletetask.ingress.ingressClass }}
  rules:
    - host: {{ .Values.deletetask.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .Release.Name }}-todo-delete-tasks-api
                port:
                  number: {{ .Values.deletetask.servicePort }}
    