apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-delete-tasks-api
spec:
  selector:
    app: {{ .Release.Name }}-app-delete-task
  ports:
  - port: {{ .Values.deletetask.servicePort }}
    targetPort: {{ .Values.deletetask.targetPort }}
