apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-get-task-ingress
spec:
  ingressClassName: {{ .Values.gettask.ingress.ingressClass }}
  rules:
  - host: {{ .Values.gettask.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Release.Name }}-get-task-api
            port: 
              number: {{ .Values.gettask.servicePort }}