apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-get-task-api
spec:
  selector:
    app: {{ .Release.Name }}-app-get-task
  ports:
  - port: {{ .Values.gettask.servicePort }}
    targetPort: {{ .Values.gettask.targetPort }}
